#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: https-with-cert-minimal
#  annotations:
#    # No TLS port annotation needed since 443 is assumed for HTTPS when another TLS option annotation is given.
#    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "545b61da-a9b2-48aa-adc6-8f749e0e2ffc"
#spec:
#  type: LoadBalancer
#  selector:
#    app: nginx-example
#  ports:
#    - name: https
#      protocol: TCP
#      port: 443
#      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingressrouter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingressrouter
  template:
    metadata:
      labels:
        app: ingressrouter
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
