---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-event-exporter
  namespace: flux-system
spec:
  targetNamespace: default
  chart: kubernetes-event-exporter
  chartRef:
    kind: OCIRepository
    name: k8s-event-exporter
    namespace: flux-system
  interval: 5m
  values:
    replicaCount: 1