---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-event-exporter
  namespace: flux-system
spec:
  targetNamespace: default
  chartRef:
    kind: OCIRepository
    name: k8s-event-exporter
    namespace: flux-system
  interval: 5m
  values:
    replicaCount: 1