---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-event-exporter
  namespace: flux-system
spec:
  targetNamespace: default
  chart:
    spec:
      chart: kubernetes-event-exporter
      version: 3.3.5
      sourceRef:
        kind: HelmRepository
        name: k8s-event-exporter
        namespace: flux-system
  interval: 5m
  values:
    replicaCount: 1